# OAuth
keboola_google_drive_writer_oauth:
    path: /oauth
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:Oauth:oauth }
    methods:  [POST]

keboola_google_drive_writer_oauth_callback:
    path: /oauth-callback
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:Oauth:oauthCallback }

keboola_google_drive_writer_oauth:
    path: /oauth/token-decrypt
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:Oauth:tokenDecrypt }
    methods:  [POST]

# External Auth
keboola_google_drive_writer_post_external_auth_link:
    path: /external-link
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:postExternalAuthLink }
    methods:  [POST]

keboola_google_drive_writer_external_auth:
    path: /external-auth
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:Oauth:externalAuth }
    methods:  [GET]

keboola_google_drive_writer_external_auth_finish:
    path: /external-finish
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:Oauth:externalAuthFinish }
    methods:  [GET]

# Configs
keboola_google_drive_writer_get_configs:
    path: /configs
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:getConfigs }
    methods:  [GET]

keboola_google_drive_writer_post_configs:
    path: /configs
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:postConfigs }
    methods:  [POST]

keboola_google_drive_writer_delete_configs:
    path: /configs/{id}
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:deleteConfig }
    methods:  [DELETE]

# Accounts
keboola_google_drive_writer_get_accounts:
    path: /accounts/{id}
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:getAccounts, id: null }
    methods:  [GET]

keboola_google_drive_writer_get_account_decrypt:
    path: /account/{id}/decrypt
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:getAccountDecrypt }
    methods:  [GET]

# Token
keboola_google_drive_writer_get_access_token:
    path: /access-token/{accountId}
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:getAccessToken }
    methods:  [GET]

keboola_google_drive_writer_post_access_token_decrypt:
    path: /access-token/decrypt
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:postAccessTokenDecrypt }
    methods:  [POST]

# Files
keboola_google_drive_writer_get_files:
    path: /files/{accountId}
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:getFiles }
    methods:  [GET]

keboola_google_drive_writer_post_file:
    path: /files/{accountId}
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:postFiles }
    methods:  [POST]

keboola_google_drive_writer_put_file:
    path: /files/{accountId}/{fileId}
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:putFiles }
    methods:  [PUT]

keboola_google_drive_writer_get_remote_files:
    path: /remote-files/{accountId}
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:getRemoteFiles }
    methods:  [GET]

keboola_google_drive_writer_get_remote_file:
    path: /remote-file/{accountId}/{fileGoogleId}
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:getRemoteFile }
    methods:  [GET]

keboola_google_drive_writer_delete_file:
    path: /files/{accountId}/{fileId}
    defaults: { _controller: KeboolaGoogleDriveWriterBundle:GoogleDriveWriter:deleteFile }
    methods:  [DELETE]
