parameters:
#    keboola_google_drive_writer.example.class: Keboola\GoogleDriveWriterBundle\Example

services:
    google_drive_writer_rest_api:
        class: Keboola\Google\DriveWriterBundle\GoogleDrive\RestApi
        arguments: [@google_rest_api]
