services:

    wr_google_drive.rest_api:
        class: Keboola\Google\DriveWriterBundle\GoogleDrive\RestApi
        arguments: [@google_rest_api, @templating]

    wr_google_drive.configuration:
        class: Keboola\Google\DriveWriterBundle\Writer\Configuration
        arguments: [%app_name%, @syrup.encryptor]

    wr_google_drive.writer:
        class: Keboola\Google\DriveWriterBundle\Writer\Writer
        arguments: [@wr_google_drive.rest_api, @logger]

    wr_google_drive.job_executor:
        class: Keboola\Google\DriveWriterBundle\Job\Executor
        arguments: [@wr_google_drive.writer, @wr_google_drive.configuration, @syrup.temp]
